version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - services/store/sqlstore/migrations

linters-settings:
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  lll:
    line-length: 180
  dupl:
    threshold: 200
  revive:
    enableAllRules: true
    rules:
      - name: exported
        disabled: true

linters:
  disable-all: true
  enable:
    - ineffassign
    - unparam
    - errcheck
    - govet
    - bodyclose
    - durationcheck
    - errorlint
    - exhaustive
    - gosec
    - makezero
    - staticcheck
    - prealloc
    - asciicheck
    - dogsled
    - dupl
    - goconst
    - gocritic
    - godot
    - err113
    - goheader
    - revive
    - nakedret
    - gomodguard
    - goprintffuncname
    - lll
    - misspell
    - nolintlint
    - unconvert
    - unused
    - whitespace
    - gocyclo

formatters:
  enable:
    - gofmt
    - goimports
